base_url = "http://127.0.0.1:1111"
title = "La izquierda ilustrada"
description = "Columna de opinión sobre la izquierda ilustrada laica racionalista en el siglo XXI"
default_language = "es"
compile_sass = false
build_search_index = true
generate_feeds = true
feed_filenames = ["atom.xml"]
taxonomies = [
  { name = "temas", feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "ayu-light", filename = "syntax-light.css" },
  { theme = "ayu-dark", filename = "syntax-dark.css" },
]
smart_punctuation = true
render_emoji = false
external_links_target_blank = true
external_links_no_follow = false
external_links_no_referrer = false

[search]
include_title = true
include_description = true
include_content = true

[extra]
author = "Italo Salgado"
author_url = ""
publication_date = "Abril 2026"
subtitle = "Mapa global, diagnóstico de la emotiocracia y el caso chileno"
math = false
mermaid = true
plotly = true
